PATH:
  DATA_PATH: C:\Files\Research\dataSet\dataSet1\brain
  SAVE_PATH: C:\Files\Research\Volume_Inpainting\VCNet_modify\out
  PTH_SAVE_PATH: C:\Files\Research\Volume_Inpainting\VCNet_modify\out
  VGG16_PATH: C:\Files\Research\Volume_Inpainting\VCNet_modify\weight\vgg16-397923af.pth

SYSTEM:
  DEVICE: cuda:0

DATASET:
  SHUFFLE: True
  ORIGIN_SHAPE: (160,224,168)   # brain
  # ORIGIN_SHAPE: (96,240,384)   # pelvic
  # ORIGIN_SHAPE: (128,128,128)   # test use
  TARGET_SHAPE: (128,128,128)

TRAIN:
  BATCH_SIZE: 2
  TEST_MODE: True
  UP_MODE: 3