PATH:
  DATA_PATH: /root/autodl-tmp/Diode/Datas/VCNet_dataSet
  SAVE_PATH: /root/autodl-tmp/Diode/Codes/Volume_Impainting/LKNet/out
  PTH_SAVE_PATH: /root/autodl-tmp/Diode/Codes/Volume_Impainting/LKNet/out
  WANDB_LOG: /root/autodl-tmp/Diode/Datas/VCNet_dataSet/log

SYSTEM:
  DEVICE: "cuda:0"

DATASET:
  SHUFFLE: True
  # ORIGIN_SHAPE: (160,224,168)   # brain
  # ORIGIN_SHAPE: (96,240,384)   # pelvic
  ORIGIN_SHAPE: (128,128,128)   # test use
  TARGET_SHAPE: (128,128,128)

TRAIN:
  BATCH_SIZE: 2
  TEST_MODE: True
  UP_MODE: 3

RUN:
  MODEL: "PconvUnet_ori"