PATH:
  DATA_PATH: /Users/wanglikai/Codes/DataSets/VCNet_dataSet
  SAVE_PATH: /Users/wanglikai/Codes/Volume_Inpainting/VCNet_modify/out
  VGG16_PATH: /Users/wanglikai/Codes/Volume_Inpainting/VCNet_modify/weights/vgg16-397923af.pth

SYSTEM:
  DEVICE: "cpu"