SYSTEM:
  NUM_GPU: 1

DATASET:
  ROOT: C:\Files\Research\dataSet\ImageNet\class1
  CONT_ROOT: C:\Files\Research\dataSet\ImageNet\class2

TRAIN:
  MASKED_PIC_PATH: C:\Files\Research\dataSet\ImageNet\masked_pic